### ISSUE TITLE
Make access_log for main configurable

### ISSUE THREAD

**Issue by hafe** [nginx/kubernetes-ingress#5625]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to globally configure log forward of access logs in a simple way. Logging high volume access logs to stdout means that they get forwarded to the log stack in Kubernetes. This can be problematic depending on the stack.

**Describe the solution you'd like**
Add a directive to the global Config map  where the main access_log directive can be overridden 

**Describe alternatives you've considered**
An alternative solution is to use a custom main template which is far from simple.

**Additional context**

**Comment by hafe** [comment]
Just to mention, I have started working on a pull request.

**Comment by danielnginx** [comment]
Thank you @hafe we will review this issue in our community call.

**Comment by danielnginx** [comment]
Hi @hafe ,

We had a chance to discuss this issue and I want to add some context.

The future state is to integrate with OpenTelemetry and streaming logs using it. We are planning on it but we do not have a timeline for this work.

Until we get to a more robust solution we are happy to accept your contribution with some conditions:

1 - We need a flag to enable the access log
2 - The default access log is always off 
3 - We must block any configuration that allows logging to files

Please let us know what you think about it?

**Comment by hafe** [comment]
Let's see:
1) already exist
2) is the inverse of today's default, I don't understand?
3) I can see if I can add some validation to not allow file

**Comment by danielnginx** [comment]
Apologies, I should mention that I was looking in the PR.

Keep the flag as it is AccessLogOff. 

Allow the access_log configuration but preventing logging to files.

**Comment by hafe** [comment]
Check latest version, only allows syslog
